services:
    redis-server:
        image: 'redis'
        volumes:
               - ./redis_data:/data
        command: ["redis-server","--save","1 1", "--protected-mode", "no"]
    node-app:
        build: ./
        image: 'docker.io/vibha.vibha5/visits'
        ports:
            - "8081:8081"